//SQLTEST  JOB (UNLAM),'TEST SQL',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID
//RUNSQL   EXEC PGM=IKJEFT01,REGION=0M
//STEPLIB  DD DSN=DSND10.SDSNLOAD,DISP=SHR
//         DD DSN=DSND10.DBDG.SDSNEXIT,DISP=SHR
//         DD DSN=DSND10.DBDG.RUNLIB.LOAD,DISP=SHR
//SYSTSPRT DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//SYSIN    DD *

  SELECT * FROM KC03B1D.USUARIOS;
  SELECT * FROM KC03B1D.LIBROS;
  SELECT * FROM KC03B1D.PRESTAMOS;

/*
//SYSTSIN  DD *
  DSN SYSTEM(DBDG)
  RUN PROGRAM(DSNTEP2) PLAN(DSNTEP13)
  END
/*
